export const DUMMY_PRODUCT = [
    {
        id: 1,
        title: "Implementasi Sertifikasi Internasional Kemampuan Bahasa Inggris TOEIC 2024 di SMK Negeri 3 Palu",
        date: "14 August 2024",
        desc: "Dalam rangka meningkatkan daya saing global di tengah perkembangan era teknologi ini, Direktorat SMK bekerjasama dengan PT International Test Center kembali menyelenggarakan kegiatan fasilitasi peningkatan kompetensi dan sertifikasi Bahasa Asing siswa SMK dengan Test of English for International Communication (TOEIC)...",
        fullDesc: "Dalam rangka meningkatkan daya saing global di tengah perkembangan era teknologi ini, Direktorat SMK bekerjasama dengan PT International Test Center kembali menyelenggarakan kegiatan fasilitasi peningkatan kompetensi dan sertifikasi Bahasa Asing siswa SMK dengan Test of English for International Communication (TOEIC). Program ini bertujuan untuk meningkatkan kemampuan bahasa Inggris siswa Sekolah Menengah Kejuruan (SMK), mempersiapkan mereka untuk dapat menghadapi tantangan global, dan memberikan sertifikasi yang diakui secara internasional melalui ujian TOEIC. Tes ini digunakan oleh banyak perusahaan dan organisasi di seluruh dunia untuk menilai kemampuan bahasa Inggris karyawan dan calon karyawan mereka. Selain itu, juga digunakan sebagai ujian syarat masuk politeknik dan pendafataran beasiswa di beberapa negara. Pada tahun ini, SMK Negeri 3 Palu turut menyemarakkan program ini dengan melibatkan sebanyak 146 siswa untuk mengikuti seleksi VIERA dan yang diumumkan lolos seleksi ada sejumlah 110 peserta didik. Sebelum para peserta didik menjalankan ujian bahasa Inggris internasional dengan TOEIC, ada sejumlah agenda Pembelajaran yang diberikan oleh tim Fasilitasi Sertifikasi TOEIC selama kurang lebih satu bulan.  Selama periode Pembelajaran, siswa bisa mengikuti sesi video conference dengan ETS Approved Facilitator—Dini Larasati dan Luthfi Ibrahim dan tim melalui Zoom dan live streaming YouTube. Paket materi pembelajaran dan persiapan TOEIC juga diberikan dalam bentuk TOEIC Practice Tests-Digital Version agar peserta didik kami siap menghadapi ujian dengan baik. Saya menjadi teknisi untuk kegiatan VIERA dan TOEIC sudah sekitar 3 atau 4 tahun terakhir. Ini merupakan pengalaman yang sangat berharga bagi saya. Menginstall aplikasinya mudah. Tidak perlu melakukan pensinkronan data. Hanya saja di sekolah kami perlu mengganti semua earphone/headset karena sudah tidak optimal digunakan (biasanya kedengaran hanya di salah satu sisi saja). Tes VIERA dan TOEIC yang difasilitasi oleh pihak ITC menjadi salah satu tolak ukur untuk kemampuan Bahasa Inggris siswa dan guru di SMK Negeri 3 Palu. Sistem ujian yang mudah diinstal dan diaplikasikan oleh tim teknisi maupun peserta tes menjadikan pelaksanaan tes lebih efektif dan efisien. Selain itu, komunikasi antara supervisor dari ITC dan tim teknisi SMK Negeri 3 Palu yang terjalin dengan baik yang ditunjukan cepat tanggap (fast response) jika terjadi pemasalan di lapangan. Harapan kami, semoga kerja sama ini dapat terlaksana secara berkesinambungan ditahun-tahun berikutnya dan kemampuan Bahasa Inggris siswa serta guru di SMK Negeri 3 Palu dapat meningkat menjadi lebih baik dan siap menghadapi era 4.0 dan Indonesia Emas."
    },
    {
        id: 2,
        title: "Grand Opening Kelas Khusus Yamaha (KKY) di SMK Negeri 3 Palu",
        date: "30 July 2023",
        desc: "Palu, 24 Juli 2023. KKY merupakan salah satu program SMK Binaan Yamaha dimana Yamaha Indonesia berkomitmen untuk memajukan pendidikan vokasi, khususnya bagi pelajar SMK secara aktif dengan memberikan standarisasi kurikulum,…",
        fullDesc: "KKY merupakan salah satu program SMK Binaan Yamaha dimana Yamaha Indonesia berkomitmen untuk memajukan pendidikan vokasi, khususnya bagi pelajar SMK secara aktif dengan memberikan standarisasi kurikulum, sarana dan prasarana teknologi otomotif untuk para siswa-siswi SMK terdaftar di seluruh Indonesia. Acara peresmian Kelas Khusus Yamaha di SMK Negeri 3 Palu dihadiri oleh Gubernur Sulawesi Tengah, yang diwakili oleh Bapak H. Mulyono, SE., Ak., MM, Kepala Dinas Pendidikan Provinsi Sulawesi Tengah Ibu Yudiawati V. Windarrusliana, SKM. M.Kes, Kepala Sekolah SMK Negeri 3 Palu, H. Hamka, S.Pd dan Pimpinan Main Dealer Yamaha Sulawesi Tengah Bapak Andi Raharja Limbunan."
    },
    {
        id: 3,
        title: "SMK NEGERI 3 PALU Mendapat Penghargaan SMK Berprestasi Pada Program Sertifikasi TOEIC Tahun 2022",
        date: "12 December 2022",
        desc: "Direktorat SMK, Direktorat Jenderal Pendidikan Vokasi, Kementerian Pendidikan dan Kebudayaan RI pada tahun 2022 bekerjasama dengan International Test Center (ITC). Yang dimana senantiasa melakukan upaya strategis untuk memastikan lulusan SMK memiliki…",
        fullDesc: "Direktorat SMK, Direktorat Jenderal Pendidikan Vokasi, Kementerian Pendidikan dan Kebudayaan RI pada tahun 2022 bekerjasama dengan International Test Center (ITC). Yang dimana senantiasa melakukan upaya strategis untuk memastikan lulusan SMK memiliki daya saing yang kuat di dunia kerja. Diantara program nyata yang secara konsisten digelar adalah program sertifikasi internasional kemampuan Bahasa Inggris bagi peserta didik SMK dengan TOEIC (Test Of English for International Communication). SMK NEGERI 3 PALU mendapatkan penghargaan sebagaimana telah diumumkan pada perhelatan acara puncak kegiatan yang ditayangkan secara langsung melalui zoom dan kanal resmi youtube Direktorat SMK pada 7 Desember 2022, Siswa tersebut antara lain atas nama : Horas Imanuel Siregar dan Moh Sayyid Maarif."
    },
    {
        id: 4,
        title: "Workshop Pengembangan Karakter dan Budaya Kerja",
        date: "22 December 2021",
        desc: "Palu- SMK Negeri 3 Palu mengadakan Workshop Penguatan Karakter SMK Pusat Keunggulan dengan peserta sejumlah 32 orang yang terdiri dari seluruh Kepala Kompetensi Kejuruan dan Kepala Bengkel yang ada di…",
        fullDesc: "Palu- SMK Negeri 3 Palu mengadakan Workshop Penguatan Karakter SMK Pusat Keunggulan dengan peserta sejumlah 32 orang yang terdiri dari seluruh Kepala Kompetensi Kejuruan dan Kepala Bengkel yang ada di SMK Negeri 3 Palu. Kegiatan ini dilaksanakan pada hari Minggu, tanggal 19 Desember 2021 dan dibuka secara resmi oleh Kepala SMK Negeri 3 Palu, Armyn, S.Pd. Dalam sambutannya, Kepala SMK Negeri 3 Palu berharap melalui kegiatan tersebut, terutama kepada guru kejuruan dapat menyiapkan softskills peserta didik melalui pembiasaan-pembiasaan karakter selama proses pembelajaran di bengkel atau praktik kejuruan. Selanjutnya kepala sekolah juga menyampaikan bahwa kegiatan ini juga digunakan untuk mereview kembali program-program yang telah disusun sebelumnya, sehingga peserta didik memiliki karakter atau softskills yang sesuai dengan yang diharapkan dalam dunia usaha saat ini."

    }
]